enabled: true
titleAndCommits: true
types:
  - chore
  - feat
  - fix
  - refactor
  - release
  - revert
scopes:
  - api
  - ci
  - core
  - deps
  - docs
  - perf
  - security
  - style
  - test
  - ui
allowMergeCommits: false
allowRevertCommits: false
